### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [totoroot/plantyhoe.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by totoroot** [comment]
Oh yeah, sure thing!
I thought I set the repo to private as I was still planning on adding a license and a readme. I should get it done by tomorrow and will notify you then.

**Comment by totoroot** [comment]
Almost forgot about it, but it's done now!
